name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select Branch to Deploy'
        required: true
        default: 'master'
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production
      sub_vertical_access:
        description: 'Enter Sub Vertical Access'
        required: true
      regulatory_url:
        description: 'Enter Regulatory URL'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --env Production

      - name: Send notification to selected environment
        if: success()
        run: |
          if [[ "${{ inputs.environment }}" == "production" ]]; then
            BASE_URL=${{ env.BASE_URL_PROD }}
            echo "Sending notification to PROD"
          else
            BASE_URL=${{ env.BASE_URL_DEV }}
            echo "Sending notification to DEV"
          fi

          curl -X 'PUT' "$BASE_URL/notification/regulatory/updated" \
          -H 'accept: */*' \
          -H "regulatorysecretskey: ${{ secrets.REGULATORY_SECRET_KEY }}" \
          -H 'Content-Type: application/json' \
          -d '{
            "sub_vertical_access": "${{ inputs.sub_vertical_access }}",
            "regulatory_url": "${{ inputs.regulatory_url }}"
          }'
