name: Airflow Pipeline Deployment

on:
  push:
    branches:
      - main
      - dev_**
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to Deploy'
        required: true
        default: 'main'
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Server
        run: |
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            SERVER_USER=${{ secrets.SERVER_USER_PROD }}
            SERVER_HOST=${{ secrets.SERVER_HOST_PROD }}
            GCP_ZONE=${{ secrets.GCP_ZONE_PROD }}
          else
            SERVER_USER=${{ secrets.SERVER_USER_DEV }}
            SERVER_HOST=${{ secrets.SERVER_HOST_DEV }}
            GCP_ZONE=""
          fi

          echo "Connecting to server: $SERVER_HOST"
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST << EOF
            set -e
            echo "Switching to root user"
            sudo -i
            
            echo "Navigating to Pipeline Repository"
            cd /home/ai-pipeline/Navirego-AI-Pipeline/
            
            echo "Stopping Existing Pipeline"
            ./stop.sh
            
            echo "Fetching Latest Changes"
            git checkout main
            git pull
            
            echo "Switching to Branch: ${{ github.event.inputs.branch || github.ref_name }}"
            git checkout ${{ github.event.inputs.branch || github.ref_name }} || git checkout -b ${{ github.event.inputs.branch || github.ref_name }}
            
            echo "Starting Pipeline for ${{ github.event.inputs.environment || 'dev' }}"
            ./start_debian.sh ${{ github.event.inputs.environment || 'dev' }}
          EOF
