name: Send Notification

on:
  workflow_dispatch:
    inputs:
      sub_vertical_access:
        description: 'Enter Sub Vertical Access'
        required: true
      regulatory_url:
        description: 'Enter Regulatory URL'
        required: true
      meta_data:
        description: 'Enter Meta-data'
        required: true
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Set BASE_URL based on environment
        run: |
          if [[ "${{ inputs.environment }}" == "production" ]]; then
            echo "BASE_URL=${{ secrets.BASE_URL_PROD }}" >> $GITHUB_ENV
            echo "Sending notification to PROD"
          else
            echo "BASE_URL=${{ secrets.BASE_URL_DEV }}" >> $GITHUB_ENV
            echo "Sending notification to DEV"
          fi

      - name: Debug BASE_URL
        run: echo "Using BASE_URL:$BASE_URL"
