name: Send Notification

on:
  workflow_dispatch:
    inputs:
      sub_vertical_access:
        description: 'Enter Sub Vertical Access'
        required: true
      regulatory_url:
        description: 'Enter Regulatory URL'
        required: true
      meta_data:
        description: 'Enter Meta-data'
        required: true
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Send notification to selected environment
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            BASE_URL=${{ secrets.BASE_URL_PROD }}
            echo "Sending notification to PROD"
          else
            BASE_URL=${{ secrets.BASE_URL_DEV }}
            echo "Sending notification to DEV"
          fi
      - name: Debug BASE_URL
        run: |
            if [[ -z "$BASE_URL" ]]; then
              echo "Error: BASE_URL is empty!"
              exit 1
            else
              echo "BASE_URL is set."
            fi
          
        
          
