name: Send Notification

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send direct notification (hardcoded test)
        run: |
          echo "Sending direct test notification to DEV"

          curl --location --request PUT 'https://zqnz0u64i7.execute-api.ap-south-1.amazonaws.com/dev/notification/regulatory/updated' \
          --header 'accept: */*' \
          --header 'regulatorysecretkey: AVL5aghuNc9Cm0FidTejMEQMLNb9Clzh' \
          --header 'Content-Type: application/json' \
          --data '{
            "sub_vertical_access": "maritime/regulatory/",
            "regulatory_url": "https://dev.navirego.com/",
            "meta_data": "maritime port regulatory"
          }'
