name: Send Notification

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Set BASE_URL based on environment
        id: set-env
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            echo "BASE_URL=${{ secrets.BASE_URL_PROD }}" >> $GITHUB_ENV
          else
            echo "BASE_URL=${{ secrets.BASE_URL_DEV }}" >> $GITHUB_ENV
          fi

      - name: Send direct notification (hardcoded test)
        run: |
          echo "Sending direct test notification to $BASE_URL"
          
          SECRET_KEY="${{ secrets.REGULATORY_SECRET_KEY }}"
          
          curl --location --request PUT "$BASE_URL/notification/regulatory/updated" \
            --header "accept: */*" \
            --header "regulatorysecretskey: $SECRET_KEY" \
            --header "Content-Type: application/json" \
            --data '{
              "sub_vertical_access": "maritime/regulatory",
              "regulatory_url": "https://dev.navirego.com",
              "meta_data": "maritime port regulatory"
            }'
