name: Send Notification

on:
  workflow_dispatch:
    inputs:
      sub_vertical_access:
        description: 'Enter Sub Vertical Access'
        required: true
      regulatory_url:
        description: 'Enter Regulatory URL'
        required: true
      meta_data:
        description: 'Enter Meta-data'
        required: true
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Set BASE_URL for environment
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            echo "BASE_URL=${{ secrets.BASE_URL_PROD }}" >> $GITHUB_ENV
            echo "Sending notification to PROD"
          else
            echo "BASE_URL=${{ secrets.BASE_URL_DEV }}" >> $GITHUB_ENV
            echo "Sending notification to DEV"
          fi

      - name: Debug BASE_URL
        run: |
          echo "Checking BASE_URL..."
          if [[ -z "$BASE_URL" ]]; then
            echo "Error: BASE_URL is empty!"
            exit 1
          else
            echo "BASE_URL is set to: $BASE_URL"
          fi
        env:
          BASE_URL: ${{ env.BASE_URL }}

      - name: Send Notification Request
        run: |
          curl -X 'PUT' "$BASE_URL/notification/regulatory/updated" \
          -H 'accept: */*' \
          -H "regulatorysecretskey: ${{ secrets.REGULATORY_SECRET_KEY }}" \
          -H 'Content-Type: application/json' \
          -d '{
            "sub_vertical_access": "${{ inputs.sub_vertical_access }}",
            "regulatory_url": "${{ inputs.regulatory_url }}",
            "meta_data": "${{ inputs.meta_data }}"
          }'
