name: Send Notification

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Send notification to selected environment
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            BASE_URL="${{ secrets.BASE_URL_PROD }}"
            echo "Sending notification to PROD"
          else
            BASE_URL="${{ secrets.BASE_URL_DEV }}"
            echo "Sending notification to DEV"
          fi

          curl --location --request PUT "$BASE_URL/dev/notification/regulatory/updated" \
          --header 'accept: */*' \
          --header 'regulatorysecretkey: ${{ secrets.REGULATORY_SECRET_KEY }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "sub_vertical_access": "maritime/regulatory/",
            "regulatory_url": "https://dev.navirego.com/",
            "meta_data": "maritime port regulatory"
          }'
